// <auto-generated />
using System;
using CarRentalSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarRentalSystem.Infrastructure.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    [Migration("20260210171544_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarRentalSystem.Domain.Entities.CarCategoryConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseDayRental")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseKmPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CarCategoryConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseDayRental = 300m,
                            BaseKmPrice = 0m,
                            Category = 1
                        },
                        new
                        {
                            Id = 2,
                            BaseDayRental = 500m,
                            BaseKmPrice = 2m,
                            Category = 2
                        },
                        new
                        {
                            Id = 3,
                            BaseDayRental = 800m,
                            BaseKmPrice = 3m,
                            Category = 3
                        });
                });

            modelBuilder.Entity("CarRentalSystem.Domain.Entities.Rental", b =>
                {
                    b.Property<string>("BookingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CarCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerSocialSecurityNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("PickupDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PickupMeterReading")
                        .HasColumnType("integer");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ReturnDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ReturnMeterReading")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookingNumber");

                    b.HasIndex("CarCategoryId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            BookingNumber = "BK0001",
                            CarCategoryId = 1,
                            CustomerSocialSecurityNumber = "SSN123456",
                            PickupDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PickupMeterReading = 0,
                            RegistrationNumber = "REG123",
                            TotalPrice = 350.00m
                        },
                        new
                        {
                            BookingNumber = "BK0002",
                            CarCategoryId = 2,
                            CustomerSocialSecurityNumber = "SSN654321",
                            PickupDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PickupMeterReading = 0,
                            RegistrationNumber = "REG456",
                            TotalPrice = 520.00m
                        });
                });

            modelBuilder.Entity("CarRentalSystem.Domain.Entities.Rental", b =>
                {
                    b.HasOne("CarRentalSystem.Domain.Entities.CarCategoryConfig", "CarCategory")
                        .WithMany()
                        .HasForeignKey("CarCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
